Chat
js-tasks-ru/nodejs-20210907_al-sosunoff pull request #11
Opened 2021-10-19 08:17 UTC by aSosunoff

2021-10-19 08:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-19 10:12 UTC, tadjik1 commented on 09-websockets/01-chat/socket.ts
> +      socket.user = checkToken(token);
классно 👍

2021-10-19 10:12 UTC, tadjik1 commented on 09-websockets/01-chat/socket.ts
> +      throw new Error('anonymous sessions are not allowed');
вот здесь вместо throw должно быть next(new Error...))

2021-10-19 10:14 UTC, tadjik1 commented on 09-websockets/01-chat/socket.ts
> +      const user = await User.findOne({ email: socket.user.email });
может можно как-то не делать каждый раз запрос к бд? я бы сделал его на этапе подключения сокета один раз. иначе тяжеловато получается.

2021-10-19 10:15 UTC, tadjik1 requested changes
@aSosunoff отметил пару моментов, готов обсудить их, хочется услышать ваше мнение как лучше сделать

2021-10-20 06:12 UTC, aSosunoff commented on 09-websockets/01-chat/socket.ts
> +      throw new Error('anonymous sessions are not allowed');
пропустил что то

2021-10-20 06:13 UTC, aSosunoff commented on 09-websockets/01-chat/socket.ts
> +      const user = await User.findOne({ email: socket.user.email });
Ага

2021-10-20 06:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-20 07:24 UTC, tadjik1 approved these changes
👍

2021-10-20 07:25 UTC, merged