Koa
js-tasks-ru/nodejs-20210907_al-sosunoff pull request #7
Opened 2021-09-30 17:11 UTC by aSosunoff

2021-10-01 14:08 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-01 14:13 UTC, tadjik1 commented on 05-koajs/01-chat-app/controller.ts
> +  await new Promise(() => {});
этот промис никогда не завершится - т.е. это утечка памяти, каждый запрос будет создавать новый промис, который будет оставаться даже после окончания работы
нам надо найти какой-то более эффективный способ, при котором промис будет завершаться

2021-10-01 14:14 UTC, tadjik1 requested changes
в целом идея правильно, но реализацию надо немного поправить

2021-10-01 15:42 UTC, aSosunoff commented on 05-koajs/01-chat-app/controller.ts
> +  await new Promise(() => {});
Потом увидел

2021-10-01 15:48 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-02 12:38 UTC, tadjik1 commented on 05-koajs/01-chat-app/controller.ts
> +  ctx.res.end(message);
а почему не просто 
`ctx.body = message`?

при работе с koa в 99% случаев нет необходимости работать с объектами req и res

2021-10-03 09:24 UTC, tadjik1 commented on 05-koajs/01-chat-app/controller.ts
> +  ctx.res.statusCode = 200;
здесь тоже достаточно просто
`ctx.body = 'ok';`

статус ответа koa проставит автоматически

2021-10-03 09:25 UTC, tadjik1 requested changes
@aSosunoff старайтесь не использовать без необходимости res.end() метод, т.к. это может привести к некорректному поведению, koa берет на себя все необходимые низкоуровневые операции, вся идея использования фреймворка построена вокруг идеи манипулирования объектом `ctx`

2021-10-03 14:24 UTC, aSosunoff commented on 05-koajs/01-chat-app/controller.ts
> +  ctx.res.end(message);
Принял

2021-10-03 14:24 UTC, aSosunoff commented on 05-koajs/01-chat-app/controller.ts
> +  ctx.res.statusCode = 200;
принял

2021-10-03 14:27 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-03 15:19 UTC, tadjik1 approved these changes
👍

2021-10-03 15:20 UTC, merged